name = "dc"
main = "docker.js"
compatibility_date = "2025-09-03"
compatibility_flags = ["streams_enable_constructors", "nodejs_compat"]
workers_dev = false
routes = [
  "hub.hxorz.cn/*",
]

[observability]
enabled = true
head_sampling_rate = 1
